addEventHandler('onClientResourceStart', resourceRoot,

function()
	local txd = engineLoadTXD('sand.txd',true)
	engineImportTXD(txd, 6118)
	local txd = engineLoadTXD('bolka.txd',true)
	engineImportTXD(txd, 6127)
	local txd = engineLoadTXD('ZDLS.txd',true)
	engineImportTXD(txd, 4821)
	local dff = engineLoadDFF('sand.dff', 0)
	engineReplaceModel(dff, 6118)
	local dff = engineLoadDFF('bolka.dff', 0)
	engineReplaceModel(dff, 6127)
	local dff = engineLoadDFF('ZDLS.dff', 0)
	engineReplaceModel(dff, 4821)
	local dff = engineLoadDFF('ZDLS2.dff', 0)
	engineReplaceModel(dff, 4160)
	local col = engineLoadCOL('sand.col')
	engineReplaceCOL(col, 6118)
	local col = engineLoadCOL('bolka.col')
	engineReplaceCOL(col, 6127)
	local col = engineLoadCOL('ZDLS.col')
	engineReplaceCOL(col, 4821)
	local col = engineLoadCOL('ZDLS2.col')
	engineReplaceCOL(col, 4160)
	engineSetModelLODDistance(6118, 8000)
	engineSetModelLODDistance(6127, 8000)
	engineSetModelLODDistance(4821, 8000)
	engineSetModelLODDistance(4160, 8000)
end)